version: "3.7"
services:
  appdb:
    image: mysql:8
    container_name: "appdb"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABAASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf

