/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface definitions {
  Error: {
    /**
     * Format: int32
     * @description HTTPステータスコード
     */
    code?: number;
    /** @description エラーメッセージ */
    message?: string;
  };
  PageInfo: {
    /**
     * Format: int32
     * @description 取得件数の上限数
     */
    total: number;
    /**
     * Format: int32
     * @description 取得したレコードの開始位置
     */
    offset: number;
  };
  Task: {
    /**
     * Format: int32
     * @description タスクのID
     */
    id?: number;
    /** @description タスクの名前 */
    title?: string;
    /** @description タスクの状態 */
    is_done?: boolean;
  };
  TaskList: {
    tasks?: definitions["Task"][];
  };
  TaskOne: {
    task?: definitions["Task"];
  };
  TaskToPost: {
    /** @description タスクの名前 */
    title: string;
    /** @description タスクの状態 */
    is_done?: boolean;
  };
  TaskToPut: {
    /** @description タスクの名前 */
    title?: string;
    /** @description タスクの状態 */
    is_done?: boolean;
  };
}

export interface parameters {
  /**
   * Format: int32
   * @description タスクID
   */
  id: number;
  /**
   * Format: int32
   * @description 取得するレコードの開始位置
   */
  offset: number;
  /**
   * Format: int32
   * @description 取得するレコードの件数
   */
  limit: number;
}

export interface operations {}

export interface external {}
